name: 'Build Effective Set Generator Docker Image'
description: 'Build and push Effective Set Generator docker image to container registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'Docker image name'
    required: false
    default: 'qubership-effective-set-generator'
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './build_effective_set_generator_java/Dockerfile'
  git-user:
    description: 'Git username for build args'
    required: false
  git-token:
    description: 'Git token for build args'
    required: false
  github-token:
    description: 'GitHub token for registry login'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: effective_set_jar
        path: downloaded_artifact

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}
    
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GIT_USER=${{ inputs.git-user }}
          GIT_TOKEN=${{ inputs.git-token }} 